
blog:
    title: Blog
    banner:
        title: Warning
        content: The blog will be down tomorrow.

spring:
    datasource:
        url: jdbc:h2:mem:mydb
        driverClassName: org.h2.Driver
        username: sa
        password: 123
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    #enabling the H2 console
    h2:
        console:
            enabled: true
            path: /h2